# NUMPY ASSIGNMENT

### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a variety of mathematical functions to operate on these arrays.

__Purpose of NumPy:__

__1.Efficient Numerical Computations:__ Python’s built-in data types (like lists) are not optimized for numerical operations, especially with large datasets.

__2.Multi-Dimensional Arrays:__ NumPy provides support for multi-dimensional arrays (1D, 2D, 3D, etc.), which are essential for representing and manipulating data in fields like physics, engineering, machine learning, and data science.

__3.Mathematical Functions:__ It offers a comprehensive set of mathematical functions to perform linear algebra, statistical analysis, random number generation, and Fourier transforms, which are essential for scientific computing.

__Advantages of NumPy:__

__1.Broadcasting:__ NumPy allows for broadcasting, a feature where smaller arrays are automatically expanded to match the dimensions of larger arrays during arithmetic operations.

__2.Integration with Other Libraries:__ NumPy serves as the foundation for other scientific computing and machine learning libraries like SciPy, pandas, TensorFlow, and scikit-learn.

__3.Indexing and Slicing:__ It provides powerful ways to index and slice arrays, making it easier to extract subsets of data or perform operations on specific elements of an array.

__How NumPy Enhances Python:__
- __Performance Boost:__ NumPy arrays are implemented in C, and operations on them are executed at speeds much faster than native Python operations on lists.
- __Array-Oriented Computing:__ It introduces an array-oriented approach, enabling Python to handle matrices and arrays efficiently, bridging the gap with languages like MATLAB and R.

### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In NumPy, both np.mean() and np.average() are used to calculate the average of an array, but they differ in terms of functionality and use cases.

__np.mean():__

- It computes the arithmetic mean (average) of the array elements along the specified axis or of the flattened array if no axis is specified.
- It does not support weighting the elements of the array.
- 
__Syntax:__
np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

__np.average():__

- It computes the weighted average of the array elements, where each element can be assigned a weight.
- If no weights are provided, it behaves like np.mean() by computing the simple arithmetic mean.
- __Syntax:__
np.average(a, axis=None, weights=None, returned=False)

__When to Use np.mean() vs np.average()__

__Use np.mean():__

- When you need to compute the simple, unweighted arithmetic mean of an array.
- In most typical cases where all elements of the array are equally important.
- It is simpler and faster when weights are not required.

__Use np.average():__

- When you need to compute a weighted average, where some elements contribute more than others.
- When you want to retrieve both the weighted average and the sum of the weights.
- np.average() is more versatile, but slower if no weights are needed, due to the additional overhead.

### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Reversing a NumPy array can be done using several techniques.

__1. Reversing a 1D NumPy Array:__

__Method 1: Using Slicing__

In [1]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)

[5 4 3 2 1]


__Method 2: Using np.flip()__

In [2]:
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)

[5 4 3 2 1]


__2. Reversing a 2D NumPy Array:__

__Method 1: Reversing Along the Rows (Axis 0)__

- Slicing 

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


- Using np.flip() with axis=0

In [5]:
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


__Method 3: Reversing Both Rows and Columns__
- Slicing

In [6]:
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


- Using np.flip() without specifying axis

In [10]:
reversed_both = np.flip(arr_2d)
print(reversed_both)



[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In NumPy, each array has a specific data type , which determines the type of elements the array can hold. 

__Determine the Data Type of a NumPy Array__

You can determine the data type of elements in a NumPy array using the dtype attribute of the array. 
__Method 1: Using the dtype Attribute__

In [11]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  

int32


__Method 2: Using np.result_type()__

In [12]:
dtype = np.result_type(np.array([1, 2, 3]), np.array([1.0, 2.0, 3.0]))
print(dtype)

float64


__Method 3: Using dtype.name for Readable Output__

In [14]:
print(arr.dtype.name) 

int32


### 5. Define nd arrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray is the central data structure used for storing and manipulating numerical data. It represents a multi-dimensional, homogeneous array of fixed-size items. Each element in an ndarray has the same data type, making it efficient for numerical computations and data analysis.

__Key Features of NumPy ndarrays__

__1.Multi-Dimensional:__

- An ndarray can have any number of dimensions (1D, 2D, 3D, etc.), making it versatile for handling a wide range of data types such as vectors, matrices, and tensors. The number of dimensions is determined by the array's shape, which is a tuple specifying the size along each dimension.
__Example:__ A 1D array is a vector, a 2D array is a matrix, and a 3D array can represent volumetric data or color images (height × width × channels).


__2.Homogeneous Data Types:__

- All elements in a NumPy array must have the same data type, such as int32, float64, etc. This uniformity allows NumPy to perform operations efficiently and optimize memory usage.

   
__3.Efficient Memory Usage:__

- NumPy arrays store elements in contiguous memory blocks, unlike Python lists, which store references to objects. This makes accessing and processing array elements much faster.

__4.Vectorized Operations:__
- NumPy supports vectorized operations, meaning you can perform element-wise operations on entire arrays without writing loops. This allows for much faster computations compared to looping through Python lists.

__5.Broadcasting:__

- Broadcasting allows operations on arrays of different shapes. Instead of manually reshaping arrays to make them compatible for element-wise operations, NumPy automatically stretches or duplicates the smaller array to match the shape of the larger array, allowing for efficient computations.

__Feature of NumPy ndarray__

- __Data Type__	Homogeneous (all elements must be of the same type).

- __Memory Efficiency__	Stores data in contiguous memory blocks, requiring less memory.	
  
- __Performance__	Much faster due to optimized C-based implementations and vectorized operations.

__Feature of NumPy Python List__

- __Data Type:__ Heterogeneous (can store elements of different types).
- __Memory Efficiency:__ Stores references to objects, leading to higher memory usage.
- __Performance:__ Slower for large-scale numerical computations because of lack of vectorization.

### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to a combination of several factors, including memory efficiency, vectorization, broadcasting, and optimized execution. 

__1. Memory Efficiency:__

Contiguous Memory Allocation: NumPy arrays store elements in a contiguous block of memory, making it easier and faster to access elements sequentially.

- Fixed Data Types: All elements in a NumPy array share the same data type (e.g., int32, float64), which enables efficient use of memory. 

- Compact Storage: NumPy arrays directly store raw data in memory without the need for object pointers (as is the case with Python lists).

__2.Speed (Vectorized Operations):__

- Element-wise Operations: NumPy supports vectorized operations, meaning you can apply mathematical functions or operators to entire arrays without needing explicit loops.
- Compiled Underlying Libraries: NumPy operations are implemented in highly optimized C and Fortran libraries, allowing for fast execution at the hardware level.

___3. Broadcasting__

- Efficient Operations Across Different Shapes: Broadcasting allows NumPy to perform operations on arrays of different shapes without copying or resizing data.

__4. Built-in Mathematical Functions__

- Optimized Math Operations: NumPy provides a wide range of built-in mathematical functions like sin, cos, log, sum, mean, and many others.

__5. Avoiding Python Loops__

- No Need for Explicit Loops: Python loops, especially for loops, introduce significant overhead due to the interpreter's management of loop variables and element access. In contrast, NumPy handles these operations internally in C, removing this overhead and speeding up computations.

__6. Handling of Large Datasets__

- Scalability: As the size of data grows, the performance gap between NumPy and Python lists widens.

__7. Parallelism and SIMD (Single Instruction, Multiple Data)__

- SIMD and Parallelism: NumPy can leverage hardware optimizations like SIMD instructions, which allow the CPU to perform the same operation on multiple data points simultaneously.

__8. Reduced Overhead for Type Checking__

- No Dynamic Type Checking: NumPy arrays enforce a single data type for all elements, which eliminates the need for frequent type checking during operations.

### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy, the vstack() and hstack() functions are used to stack arrays along different axes, enabling easy concatenation of arrays either vertically or horizontally.\
__1. np.vstack() (Vertical Stacking)__
- Purpose: Stacks arrays vertically (row-wise) along the first axis (axis 0).
- Usage: It combines arrays with the same number of columns by placing one array on top of the other.
- Example:

In [15]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_vstack_1d = np.vstack((arr1, arr2))
print("Vertical Stacking (1D arrays):\n", result_vstack_1d)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])
result_vstack_2d = np.vstack((arr3, arr4))
print("\nVertical Stacking (2D arrays):\n", result_vstack_2d)


Vertical Stacking (1D arrays):
 [[1 2 3]
 [4 5 6]]

Vertical Stacking (2D arrays):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


__2. np.hstack() (Horizontal Stacking)__
- Purpose: Stacks arrays horizontally (column-wise) along the second axis (axis 1).
- Usage: It combines arrays with the same number of rows by placing one array next to the other (side by side).
- Example:

In [16]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_hstack_1d = np.hstack((arr1, arr2))
print("Horizontal Stacking (1D arrays):\n", result_hstack_1d)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])
result_hstack_2d = np.hstack((arr3, arr4))
print("\nHorizontal Stacking (2D arrays):\n", result_hstack_2d)

Horizontal Stacking (1D arrays):
 [1 2 3 4 5 6]

Horizontal Stacking (2D arrays):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In NumPy, the fliplr() and flipud() methods are used to flip arrays along different axes.

__1. np.fliplr() (Flip Left to Right)__
- __Purpose:__ fliplr() flips an array horizontally by reversing the order of columns, i.e., it reflects the array along the vertical axis (left-right flip).
- Applicable: It is primarily used for 2D arrays or higher dimensions where the second axis (axis 1, columns) can be reversed. This function does not work on 1D arrays, as there's no second axis.
  
__Effect on 2D Arrays:__
- __Original Array:__ The first column becomes the last, the second column becomes the second-to-last, and so on.

In [17]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_fliplr = np.fliplr(arr_2d)
print("Original 2D Array:\n", arr_2d)
print("After fliplr:\n", result_fliplr)

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After fliplr:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


__Effect on 3D Arrays:__

- __fliplr()__ flips the second axis (columns) for every 2D slice of the 3D array.

In [18]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result_fliplr_3d = np.fliplr(arr_3d)
print("After fliplr (3D array):\n", result_fliplr_3d)

After fliplr (3D array):
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]


__2. np.flipud() (Flip Up to Down)__
- __Purpose:__ flipud() flips an array vertically by reversing the order of rows, i.e., it reflects the array along the horizontal axis (top-bottom flip).
- __Applicable:__ It can be applied to both 1D and 2D arrays (or higher dimensions). For 1D arrays, it reverses the order of elements. For 2D arrays, it reverses the rows.
 
__Effect on 1D Arrays:__
- __Original Array:__ The first element becomes the last, the second element becomes the second-to-last, and so on.

In [19]:
arr_1d = np.array([1, 2, 3, 4, 5])
result_flipud_1d = np.flipud(arr_1d)
print("Original 1D Array:\n", arr_1d)
print("After flipud:\n", result_flipud_1d)

Original 1D Array:
 [1 2 3 4 5]
After flipud:
 [5 4 3 2 1]


__Effect on 2D Arrays:__
- __Original Array:__ The first row becomes the last, the second row becomes the second-to-last, and so on.

In [20]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_flipud = np.flipud(arr_2d)
print("Original 2D Array:\n", arr_2d)
print("After flipud:\n", result_flipud)

Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After flipud:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike the split() function, which requires the splits to be equal, array_split() is more flexible and can handle uneven splits by distributing the remainder across the sub-arrays.

__Syntax:__

In [ ]:
numpy.array_split(arr, indices_or_sections, axis=0)

- __arr:__ The input array to be split.

- __indices_or_sections:__ This determines how the array will be split. It can either be:
    - An integer specifying the number of sub-arrays to split into.
    - A list of indices where the splits will occur.
- __axis:__ The axis along which to split the array. By default, it's axis 0 (rows for 2D arrays)

__How array_split() Handles Uneven Splits:__

When the array length is not evenly divisible by the number of requested splits, array_split() distributes the extra elements to the first few sub-arrays. The sub-arrays that receive extra elements will have one more element than the others.

__Example:__ Even Split Using array_split():

In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.array_split(arr, 3)
print("Split arrays:", split_arrays)

Split arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


__Example:__ Uneven Split Using array_split()

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
split_arrays = np.array_split(arr, 3)
print("Split arrays:", split_arrays)

Split arrays: [array([1, 2, 3]), array([4, 5]), array([6, 7])]


### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization and broadcasting are powerful concepts in NumPy that significantly enhance the efficiency and performance of array operations.

__1. Vectorization__

__Concept:__

Vectorization refers to the practice of performing operations on entire arrays or large blocks of data in a single operation, rather than performing the operation element-wise in a loop. It leverages low-level, compiled code and optimized libraries to perform these operations efficiently.

In [26]:
import numpy as np
arr = np.arange(1000000)
squared = arr ** 2

__Benefits:__

- __Performance:__ Vectorized operations are generally much faster because they avoid the overhead of Python loops and make use of optimized low-level operations.
- __Readability:__ Vectorized code is more concise and easier to understand compared to loop-based approaches.

__2. Broadcasting__
__Concept:__

- __Broadcasting__ is a technique used to perform operations on arrays of different shapes in a consistent way. It allows NumPy to handle arithmetic operations between arrays of different sizes without the need for explicit resizing or replication of data.

In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4])
scalar = 5
result = arr + scalar
print(result)

[6 7 8 9]


__Benefits:__

- __Efficiency:__ Broadcasting avoids the need to manually expand arrays or use extra memory for large datasets. It performs operations efficiently by leveraging low-level optimizations.\

- __Simplicity:__ Simplifies code by allowing operations on arrays of different shapes without explicit looping or data manipulation.